name: hop_phuong
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_localizations:
    sdk: flutter
  isar: 3.1.0
  isar_flutter_libs: 3.1.0
  intl: ^0.20.2
  lunar_calendar:
    path: packages/lunar_calendar
  excel: ^4.0.6
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_generator: 3.1.0

flutter:
  uses-material-design: true